harnessApiVersion: '1.0'
type: BASIC
concurrencyStrategy: INFRA
envName: amazon
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupNames:
  - Account Administrator
phases:
- type: CUSTOM
  computeProviderName: DUMMY_CLOUD_PROVIDER
  daemonSet: false
  infraDefinitionName: nomad
  name: Phase 1
  phaseSteps:
  - type: CUSTOM_DEPLOYMENT_PHASE_STEP
    name: Deploy
    steps:
    - type: SHELL_SCRIPT
      name: Nomad and Docker Build
      properties:
        commandPath: null
        connectionAttributeName: null
        executeOnDelegate: true
        host: null
        publishAsVar: false
        sshKeyRefName: null
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        timeoutMillis: 600000
      templateUri: cassie-test/Nomad and Docker Build:latest
      templateVariables:
      - name: DEPLOY_ID
        value: ${context.DEPLOY_CONTROL.DEPLOY_ID}, OVERRIDE_DEPLOY_TYPE
    - type: SHELL_SCRIPT
      name: Deploy Service
      properties:
        commandPath: null
        connectionAttributeName: null
        executeOnDelegate: true
        host: null
        publishAsVar: false
        sshKeyRefName: null
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        timeoutMillis: 600000
      templateUri: cassie-test/Deploy Service:latest
    stepsInParallel: false
  - type: CUSTOM_DEPLOYMENT_PHASE_STEP
    name: Verify Service
    stepsInParallel: false
  - type: CUSTOM_DEPLOYMENT_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: api
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_CUSTOM}
    fieldName: infraDefinitionId
    metadata:
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
rollbackPhases:
- type: CUSTOM
  computeProviderName: DUMMY_CLOUD_PROVIDER
  daemonSet: false
  infraDefinitionName: nomad
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: CUSTOM_DEPLOYMENT_PHASE_STEP
    name: Rollback Service
    stepsInParallel: false
  provisionNodes: false
  serviceName: api
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_CUSTOM}
    fieldName: infraDefinitionId
    metadata:
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
templateExpressions:
- expression: ${Environment}
  fieldName: envId
  metadata:
  - name: relatedField
    value: ${InfraDefinition_CUSTOM}
  - name: entityType
    value: ENVIRONMENT
- expression: ${InfraDefinition_CUSTOM}
  fieldName: infraDefinitionId
  metadata:
  - name: relatedField
  - name: entityType
    value: INFRASTRUCTURE_DEFINITION
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Environment entity
  fixed: false
  mandatory: true
  name: Environment
- type: ENTITY
  description: Variable for Infrastructure Definition entity
  fixed: false
  mandatory: true
  name: InfraDefinition_CUSTOM
